# Generated by Django 5.2.7 on 2025-10-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='climates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='name',
            field=models.CharField(default='Unnamed Planet', max_length=30),
        ),
        migrations.AddField(
            model_name='planets',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planets',
            name='terrains',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
